server:
  port: 8099
swagger2:
  title: API
  description: description
  version: 0.1
  basePackage: com.z94
  
spring:
  datasource:
    url: jdbc:mysql://rm-wz9k5gu561tue4swco.mysql.rds.aliyuncs.com:3306/boot
    username: root
    password: ''
    
mybatis:
  mapper-locations: classpath*:/mappers/*Mapper.xml
  